<?php

/**
 * Provide a public-facing view for the plugin
 *
 * This file is used to markup the public-facing aspects of the plugin.
 *
 * @link       https://racmanuel.dev
 * @since      1.0.0
 *
 * @package    Buen_Fin_Woo
 * @subpackage Buen_Fin_Woo/public/partials
 */
?>

<!-- This message is generated by Buen Fin plugin -->
<div class="row" id="msi-woocommerce">
    <div class="column">
        <div class="row">
            <img src="<?php echo esc_url($image); ?>" class="img-msi-woocommerce" width="50"></img>
            <span class="title-msi-woocommerce"><?php echo esc_html($TITLE_OPTION); ?></span>
        </div>
        <?php if ($MSIR3_OPTION == 'no' && $MSIR6_OPTION == 'no' && $MSIR9_OPTION == 'no' && $MSIR12_OPTION == 'no'): ?>
        <div class="row set_hide">
            <? else: ?>
            <div class="row">
                <?php endif;?>
                <div class="column msi-woocommerce">
                    <table>
                        <?php if ($MSIR3_OPTION == 'yes'): ?>
                        <!-- 3 Meses Sin Intereses -->
                        <tr>
                            <td class="buen-fin-woo-price">
                                <?php echo esc_html($SYMBOL_CURRENCY); ?>
                                <?php echo esc_html($MSI3); ?> 
                                <?php echo esc_html($CURRENCY);?>
                            </td>
                            <td><?php echo esc_html_e('a 3 Meses sin Intereses.', 'buen-fin-woo'); ?></td>
                        </tr>
                        <?php endif;?>
                        <?php if ($MSIR6_OPTION == 'yes'): ?>
                        <!-- 6 Meses Sin Intereses -->
                        <tr>
                            <td class="buen-fin-woo-price">
                                <?php echo esc_html($SYMBOL_CURRENCY); ?>
                                <?php echo esc_html($MSI6); ?> 
                                <?php echo esc_html($CURRENCY);?>
                            </td>
                            <td><?php echo esc_html_e('a 6 Meses sin Intereses.', 'buen-fin-woo'); ?></td>
                        </tr>
                        <?php endif;?>
                        <?php if ($MSIR9_OPTION == 'yes'): ?>
                        <!-- 9 Meses Sin Intereses -->
                        <tr>
                            <td class="buen-fin-woo-price">
                                <?php echo esc_html($SYMBOL_CURRENCY); ?>
                                <?php echo esc_html($MSI9); ?> 
                                <?php echo esc_html($CURRENCY);?>
                            </td>
                            <td><?php echo esc_html_e('a 9 Meses sin Intereses.', 'buen-fin-woo'); ?></td>
                        </tr>
                        <?php endif;?>
                        <?php if ($MSIR12_OPTION == 'yes'): ?>
                        <!-- 12 Meses Sin Intereses -->
                        <tr>
                            <td class="buen-fin-woo-price">
                                <?php echo esc_html($SYMBOL_CURRENCY); ?>
                                <?php echo esc_html($MSI12); ?> 
                                <?php echo esc_html($CURRENCY);?>
                            </td>
                            <td><?php echo esc_html_e('a 12 Meses sin Intereses.', 'buen-fin-woo'); ?></td>
                        </tr>
                        <?php endif;?>
                    </table>
                </div>
            </div>
            <div class="row">
                <span class="conditions-msi-woocommerce">
                    <?php if ($product_type == 'variable'): ?>
                      <?php echo esc_html_e('Los precios expresados son tomando el producto de menor costo.', 'buen-fin-woo'); ?>
                    <?php endif;?>
                    <?php echo esc_html_e('*Promocion valida solo con tarjetas de crédito y bancos participantes del 10 al 16 de Noviembre del', 'buen-fin-woo'); ?>
                    <?php echo wp_date(__('Y', 'buen-fin-woo')); ?>.
                    <?php echo esc_html($TERMS_OPTION); ?>
                </span>
            </div>
        </div>
    </div>