<?php

/**
 * Provide a public-facing view for the plugin
 *
 * This file is used to markup the public-facing aspects of the plugin.
 *
 * @link       https://racmanuel.dev
 * @since      1.0.0
 *
 * @package    Buen_Fin_Woo
 * @subpackage Buen_Fin_Woo/public/partials
 */
?>

<!-- This message is generated by Buen Fin plugin -->
<div class="row" id="msi-woocommerce">
    <div class="column">
        <div class="row">
            <img src="<?= $image ?>" class="img-msi-woocommerce"></img>
            <h2 class="title-msi-woocommerce">¡Aprovecha los precios del Buen Fin + MSI!</h2>
        </div>
        <div class="row">
            <div class="column msi-woocommerce">
                <span>
                    <strong>$ <?= $MSIR3 ?> MXN </strong> a <strong>3 MSI</strong>.
                </span>
            </div>
            <div class="column msi-woocommerce">
                <span>
                    <strong>$ <?= $MSIR6 ?> MXN </strong> a <strong>6 MSI</strong>.
                </span>
            </div>
            <div class="column msi-woocommerce">
                <span>
                    <strong>$ <?= $MSIR12 ?> MXN </strong>a <strong>12 MSI</strong>.
                </span>
            </div>
        </div>
        <div class="row">
            <span class="conditions-msi-woocommerce">* Promocion valida solo con tarjetas de crédito y bancos
                participantes del 1 al 16 de noviembre de 2021.</span>
        </div>
    </div>
</div>